# Generated by Django 5.1.1 on 2025-05-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_alter_userreg_images_alter_userreg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='is_set_auth',
            field=models.BooleanField(default=False),
        ),
    ]
