# Generated by Django 5.0.6 on 2024-07-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Systemchat',
            fields=[
                ('chatid', models.AutoField(primary_key=True, serialize=False)),
                ('fromuser', models.CharField(max_length=15)),
                ('touser', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=500)),
                ('chat_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Userreg',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('phoneno', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('secure_question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=15)),
                ('images', models.CharField(max_length=50)),
            ],
        ),
    ]
