# Generated by Django 5.0.6 on 2024-07-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='images',
            field=models.CharField(default='user.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='status',
            field=models.CharField(default='offline', max_length=15),
        ),
    ]
